"""
XGBoost Phishing Detection Model

This module trains and evaluates an XGBoost classifier for detecting phishing accounts
using graph embeddings generated by the SGDiT-SGCR algorithm.

Key features:
- Loads graph embeddings and account labels
- Supports hyperparameter optimization with Optuna
- Evaluates performance at multiple thresholds
- Saves misclassified instances for analysis
- Provides detailed metrics including confusion matrix
"""

import numpy as np
import pickle
import argparse
from sklearn.model_selection import train_test_split, cross_val_score
from xgboost import XGBClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report, confusion_matrix
import sys
import json
import wandb
import requests
import os
import optuna
from optuna.samplers import TPESampler

def parse_args():
    """
    Parse command-line arguments for XGBoost phishing detection.
    
    Returns:
        argparse.Namespace: Parsed arguments containing:
            - dataset: Dataset identifier
            - embedding_file: Path to node embeddings
            - tag_file: Path to labels (0=normal, 1=phisher)
            - feature_select: Feature selection strategy
            - ratio: Class balance ratio
            - project: Weights & Biases project name
            - n_estimators: Number of boosting trees
            - max_depth: Maximum tree depth
            - learning_rate: Learning rate (eta)
            - subsample: Row sampling ratio
            - colsample_bytree: Column sampling ratio
            - optimize: Whether to run hyperparameter optimization
            - n_trials: Number of Optuna optimization trials
    """
    parser = argparse.ArgumentParser(description='XGBoost Classifier for Graph Embeddings')
    
    # Dataset configuration
    parser.add_argument("--dataset", type=str, default="MulDiGraph", choices=["B4E", "MulDiGraph", "TXNT"],
                        help="Dataset to use (default: B4E)")
    parser.add_argument("--embedding_file", type=str, default=None,
                        help="Path to embedding file (default: ../data/dataset/Data_after_FE/graph_emb.txt)")
    parser.add_argument("--tag_file", type=str, default=None,
                        help="Path to tag file (default: ../data/processed_data/account_tags.pkl)")
    
    # Feature and experiment configuration
    parser.add_argument("--feature_select", type=str, default="Selected Features",
                        help="Feature selection method (default: Selected Features)")
    parser.add_argument("--ratio", type=str, default="5:5",
                            help="Ratio of normal accounts to phisher accounts (default: 5:5)")
    parser.add_argument("--project", type=str, default="SGDiT SGCR",
                        help="WandB project name (default: Feature Engineer GMM)")
    
    # XGBoost hyperparameters (used when not optimizing)
    parser.add_argument("--n_estimators", type=int, default=400,
                        help="Number of gradient boosted trees (default: 100)")
    parser.add_argument("--max_depth", type=int, default=6,
                        help="Maximum tree depth (default: 6)")
    parser.add_argument("--learning_rate", type=float, default=0.3,
                        help="Boosting learning rate (default: 0.3)")
    parser.add_argument("--subsample", type=float, default=1.0,
                        help="Subsample ratio of training instances (default: 1.0)")
    parser.add_argument("--colsample_bytree", type=float, default=1.0,
                        help="Subsample ratio of columns when constructing each tree (default: 1.0)")
    
    # Hyperparameter optimization
    parser.add_argument("--optimize", action="store_true",
                        help="Enable hyperparameter optimization with Optuna")
    parser.add_argument("--n_trials", type=int, default=50,
                        help="Number of optimization trials (default: 50)")
    
    args = parser.parse_args()

    # Set default file paths based on dataset if not provided
    if args.embedding_file is None:
        args.embedding_file = f"../data/dataset/Data_after_FE/graph_emb.txt"
    if args.tag_file is None:
        args.tag_file = f"../data/processed_data/account_tags.pkl"

    return args

def save_misclassified_indices(misclassified_indices, y_true, y_pred, original_indices, dataset_name, split_name, threshold):
    """
    Save misclassified instance information to JSON file for error analysis.
    
    This function records which accounts were incorrectly classified, allowing
    for detailed post-hoc analysis of model failures.
    
    Args:
        misclassified_indices (numpy.ndarray): Boolean mask or indices of misclassified samples
        y_true (numpy.ndarray): True labels
        y_pred (numpy.ndarray): Predicted labels
        original_indices (list): Original account indices in the full dataset
        dataset_name (str): Name of the dataset
        split_name (str): Name of the data split (e.g., 'Train', 'Test')
        threshold (float): Classification threshold used
    
    Saves:
        JSON file containing:
        - Total number of misclassifications
        - Indices of misclassified samples
        - True vs predicted labels for each misclassification
    """
    filename = f"misclassified_{dataset_name}_{split_name}_threshold_{threshold:.1f}_xgboost.json"
    
    # Chuyển đổi boolean mask thành indices nếu cần
    if misclassified_indices.dtype == bool:
        misclassified_pos = np.where(misclassified_indices)[0]
    else:
        misclassified_pos = misclassified_indices
    
    result = {
        "dataset": dataset_name,
        "split": split_name, 
        "threshold": float(threshold),
        "total_misclassified": int(len(misclassified_pos)),
        "misclassified_indices": [int(x) for x in misclassified_pos.tolist()],
        "original_indices": [int(original_indices[i]) for i in misclassified_pos],
        "true_labels": [int(y_true[i]) for i in misclassified_pos],
        "predicted_labels": [int(y_pred[i]) for i in misclassified_pos]
    }
    
    with open(filename, 'w') as f:
        json.dump(result, f, indent=2)
    
    print(f"Saved {len(misclassified_pos)} misclassified indices to {filename}")

def get_max_index(tag_file):
    """
    Get the maximum index from the tag file.
    
    Args:
        tag_file (str): Path to pickle file containing account labels
    
    Returns:
        int: Maximum index in the dataset
    """
    with open(tag_file, 'rb') as f:
        tags = pickle.load(f)
    return len(tags) - 1

def get_embedding_dim(embedding_file):
    """
    Determine the dimensionality of embeddings by reading the first line.
    
    Args:
        embedding_file (str): Path to embedding file (format: "index feat1 feat2 ...")
    
    Returns:
        int: Number of features per embedding
    """
    with open(embedding_file, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) > 1:
                return len(parts) - 1  # Subtract 1 for the index column
    return 0

def load_embeddings(file_path, max_index, embedding_dim):
    """
    Load node embeddings from text file into dictionary.
    
    Expected format: "node_id feat1 feat2 feat3 ..."
    
    Args:
        file_path (str): Path to embedding file
        max_index (int): Maximum expected node index (for validation)
        embedding_dim (int): Expected dimensionality of embeddings
    
    Returns:
        dict: Dictionary mapping node_id -> embedding vector (numpy array)
    """
    embeddings = {}
    with open(file_path, 'r') as f:
        for line in f:
            parts = line.strip().split()
            index = int(parts[0])
            embedding = np.array([float(x) for x in parts[1:]], dtype=np.float32)
            # Only store embeddings with correct dimensionality
            if len(embedding) == embedding_dim:
                embeddings[index] = embedding
    print(f"Number of embeddings loaded: {len(embeddings)}", end='\r')
    return embeddings

def load_tags(file_path, max_index):
    """
    Load account labels from pickle file.
    
    Args:
        file_path (str): Path to pickle file containing labels
        max_index (int): Maximum expected index (currently unused)
    
    Returns:
        dict: Dictionary mapping node_id -> label (0=normal, 1=phisher)
    """
    with open(file_path, 'rb') as f:
        tags = pickle.load(f)
    print(f"Number of tags loaded: {len(tags)}", end='\r')
    filtered_tags = {k: v for k, v in tags.items()}
    return filtered_tags

def prepare_data(embeddings, tags):
    """
    Prepare feature matrix and label vector for training.
    
    Aligns embeddings and tags by taking the intersection of their keys.
    Only nodes that have both an embedding and a label are included.
    
    Args:
        embeddings (dict): Dictionary of node embeddings
        tags (dict): Dictionary of node labels
    
    Returns:
        tuple: (X, y, valid_indices)
            - X (numpy.ndarray): Feature matrix (n_samples, n_features)
            - y (numpy.ndarray): Label vector (n_samples,)
            - valid_indices (list): List of node IDs corresponding to rows in X and y
    """
    # Find nodes that have both embeddings and labels
    valid_indices = sorted(set(embeddings.keys()) & set(tags.keys()))

    X = np.zeros((len(valid_indices), len(list(embeddings.values())[0])), dtype=np.float32)
    y = np.zeros(len(valid_indices), dtype=np.int32)

    for i, idx in enumerate(valid_indices):
        X[i] = embeddings[idx]
        y[i] = tags[idx]

    return X, y, valid_indices

def optimize_hyperparameters(X_train, y_train, n_trials=50):
    """
    Optimize XGBoost hyperparameters using Optuna framework.
    
    Uses Tree-structured Parzen Estimator (TPE) for efficient hyperparameter search.
    Optimizes for F1 score using 5-fold cross-validation.
    
    Search space:
    - n_estimators: [50, 300] - Number of trees
    - max_depth: [3, 12] - Tree depth (controls complexity)
    - learning_rate: [0.01, 0.3] - Step size shrinkage
    - subsample: [0.6, 1.0] - Row sampling ratio
    - colsample_bytree: [0.6, 1.0] - Column sampling ratio
    - reg_alpha: [0.0, 1.0] - L1 regularization
    - reg_lambda: [0.0, 1.0] - L2 regularization
    
    Args:
        X_train (numpy.ndarray): Training features
        y_train (numpy.ndarray): Training labels
        n_trials (int): Number of optimization trials to run
    
    Returns:
        dict: Best hyperparameters found
    """
    def objective(trial):
        """
        Objective function for Optuna optimization.
        
        Args:
            trial: Optuna trial object for suggesting hyperparameters
        
        Returns:
            float: Mean F1 score from 5-fold cross-validation
        """
        # Define search space for hyperparameters
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 50, 300),
            'max_depth': trial.suggest_int('max_depth', 3, 12),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
            'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0),
            'random_state': 42,
            'n_jobs': -1,
            'eval_metric': 'logloss'
        }
        
        # Tạo model với hyperparameters được suggest
        model = XGBClassifier(**params)
        
        # Sử dụng cross-validation để đánh giá
        scores = cross_val_score(model, X_train, y_train, cv=5, scoring='f1', n_jobs=-1)
        return scores.mean()
    
    # Tạo study và optimize
    study = optuna.create_study(
        direction='maximize',
        sampler=TPESampler(seed=42)
    )
    
    print(f"Starting hyperparameter optimization with {n_trials} trials...")
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    
    print(f"\nOptimization completed!")
    print(f"Best F1 score: {study.best_value:.4f}")
    print(f"Best parameters: {study.best_params}")
    
    return study.best_params

def train_and_evaluate(X, y, valid_indices, dataset_name, args):
    """
    Train XGBoost model and evaluate performance at multiple thresholds.
    
    Workflow:
    1. Split data into train/test (80/20)
    2. Optionally optimize hyperparameters with Optuna
    3. Train XGBoost classifier
    4. Evaluate at thresholds from 0.1 to 0.9
    5. Save misclassified instances at threshold 0.5
    6. Display feature importance
    
    Args:
        X (numpy.ndarray): Feature matrix
        y (numpy.ndarray): Labels (0=normal, 1=phisher)
        valid_indices (list): Node IDs corresponding to X and y
        dataset_name (str): Dataset identifier
        args (argparse.Namespace): Command-line arguments
    
    Returns:
        tuple: (test_precision, test_recall, test_f1) at threshold 0.5
    """
    # Split data: 80% train, 20% test with stratification
    X_train, X_test, y_train, y_test, indices_train, indices_test = train_test_split(
        X, y, valid_indices, test_size=0.2, random_state=42)

    print(f"Train size: {len(X_train)} ({len(X_train)/len(X)*100:.1f}%)")
    print(f"Test size: {len(X_test)} ({len(X_test)/len(X)*100:.1f}%)")

    # Hyperparameter optimization: Use Optuna if requested, otherwise use manual parameters
    if args.optimize:
        best_params = optimize_hyperparameters(X_train, y_train, args.n_trials)
        
        # Khởi tạo model với best parameters
        model = XGBClassifier(
            **best_params,
            random_state=42,
            n_jobs=-1,
            eval_metric='logloss'
        )
    else:
        # Sử dụng parameters mặc định hoặc từ command line
        model = XGBClassifier(
            n_estimators=args.n_estimators,
            max_depth=args.max_depth,
            learning_rate=args.learning_rate,
            subsample=args.subsample,
            colsample_bytree=args.colsample_bytree,
            random_state=42,
            n_jobs=-1,
            eval_metric='logloss'
        )
    
    # Training
    model.fit(X_train, y_train)

    def evaluate_split(X_split, y_split, split_indices, split_name):
        """
        Evaluate model performance on a data split at multiple thresholds.
        
        Tests classification thresholds from 0.1 to 0.9 to analyze precision-recall tradeoff.
        Saves detailed metrics and misclassifications at threshold 0.5.
        
        Args:
            X_split (numpy.ndarray): Feature matrix for this split
            y_split (numpy.ndarray): True labels
            split_indices (list): Node indices for this split
            split_name (str): Name of the split (e.g., 'Train', 'Test')
        
        Returns:
            tuple: (precision, recall, f1) for label 1 (phisher) at threshold 0.5
        """
        # Get predicted probabilities for positive class (phisher)
        y_prob = model.predict_proba(X_split)[:, 1]
        # Test multiple thresholds to understand performance tradeoffs
        thresholds = np.arange(0.1, 1.0, 0.1)
        target_threshold = 0.5  # Standard threshold for detailed analysis
        precision_03 = 0.0
        recall_03 = 0.0
        f1_03 = 0.0

        print(f"\n=== {split_name} Split Results ===")
        # Iterate through thresholds to see precision-recall tradeoff
        for threshold in thresholds:
            # Convert probabilities to binary predictions using current threshold
            y_pred = (y_prob >= threshold).astype(int)
            print(f"\nThreshold: {threshold:.2f}")
            print(classification_report(y_split, y_pred, zero_division=0, digits=4))

            if abs(threshold - target_threshold) < 1e-5:
                precision_03 = precision_score(y_split, y_pred, labels=[1], average=None, zero_division=0)[0] if 1 in y_split else 0.0
                recall_03 = recall_score(y_split, y_pred, labels=[1], average=None, zero_division=0)[0] if 1 in y_split else 0.0
                f1_03 = f1_score(y_split, y_pred, labels=[1], average=None, zero_division=0)[0] if 1 in y_split else 0.0
                
                # Tìm các indices bị dự đoán sai
                misclassified_mask = (y_split != y_pred)
                misclassified_local_indices = np.where(misclassified_mask)[0]
                misclassified_original_indices = np.array(split_indices)[misclassified_local_indices]
                
                # Lưu các indices bị dự đoán sai
                save_misclassified_indices(
                    misclassified_mask, y_split, y_pred, 
                    split_indices, dataset_name, split_name, target_threshold
                )
                
                # Confusion Matrix analysis for threshold 0.5
                # Matrix layout: [[TN, FP], [FN, TP]]
                cm = confusion_matrix(y_split, y_pred)
                cm_array = np.array(cm)
                print(f"\n=== Confusion Matrix (Threshold 0.5) - {split_name} ===")
                print(f"Numpy Array:\n{cm_array}")
                
                if cm_array.shape == (2, 2):
                    tn, fp, fn, tp = cm_array.ravel()
                    print(f"True Negatives (TN): {tn}")
                    print(f"False Positives (FP): {fp}")
                    print(f"False Negatives (FN): {fn}")
                    print(f"True Positives (TP): {tp}")
                    print(f"Total samples: {tn + fp + fn + tp}")
                
                print(f"\nThreshold 0.5 - Label 1 Results:")
                print(f"Label 1 - Precision: {precision_03:.4f}")
                print(f"Label 1 - Recall: {recall_03:.4f}")
                print(f"Label 1 - F1 Score: {f1_03:.4f}")
        
        return precision_03, recall_03, f1_03

    # Đánh giá trên test set  
    test_precision, test_recall, test_f1 = evaluate_split(X_test, y_test, indices_test, "Test")

    # Feature importance analysis
    # XGBoost provides importance scores based on feature usage in trees
    feature_importance = model.feature_importances_
    print(f"\nTop 10 Most Important Features:")
    important_features = np.argsort(feature_importance)[-10:][::-1]
    for i, feat_idx in enumerate(important_features):
        print(f"  {i+1}. Feature {feat_idx}: {feature_importance[feat_idx]:.4f}")

    return test_precision, test_recall, test_f1

def main():
    """
    Main execution function for XGBoost phishing detection.
    
    Pipeline:
    1. Parse command-line arguments
    2. Load embeddings and labels
    3. Prepare training data
    4. Train and evaluate model (with or without optimization)
    5. Display final metrics
    """
    args = parse_args()
    embedding_file = args.embedding_file
    tag_file = args.tag_file

    max_index = get_max_index(tag_file)
    print(f"Max index from tags: {max_index}")
    embedding_dim = get_embedding_dim(embedding_file)
    print(f"Embedding dimension: {embedding_dim}")

    embeddings = load_embeddings(embedding_file, max_index, embedding_dim)
    tags = load_tags(tag_file, max_index)
    print(f"Number of tags loaded: {len(tags)}")

    X, y, valid_indices = prepare_data(embeddings, tags)

    if args.optimize:
        print(f"\nOptuna Optimization Settings:")
        print(f"  n_trials: {args.n_trials}")
        print(f"  Optimization enabled: True")
    else:
        print(f"\nXGBoost Parameters (Manual):")
        print(f"  n_estimators: {args.n_estimators}")
        print(f"  max_depth: {args.max_depth}")
        print(f"  learning_rate: {args.learning_rate}")
        print(f"  subsample: {args.subsample}")
        print(f"  colsample_bytree: {args.colsample_bytree}")

    test_precision, test_recall, test_f1 = train_and_evaluate(X, y, valid_indices, args.dataset, args)

    print(f"\n=== Final Metrics for Label 1 (Threshold 0.5) ===")
    print(f"Test Set:")
    print(f"  Precision: {test_precision:.4f}")
    print(f"  Recall: {test_recall:.4f}")
    print(f"  F1 Score: {test_f1:.4f}")

if __name__ == '__main__':
    main()